// AUTO-GENERATED by scripts/gen-image-sizes.py — do not edit by hand.
// Regenerate after adding, removing, or replacing portfolio photos:
//   python scripts/gen-image-sizes.py

export type ImageSize = { w: number; h: number };

export const imageSizes: Record<string, ImageSize> = {
  "/images/portfolio/kfc-amk/1.jpg": { w: 1600, h: 1200 },
  "/images/portfolio/kfc-amk/2.jpg": { w: 1600, h: 1200 },
  "/images/portfolio/kfc-csp/1.jpg": { w: 1125, h: 2000 },
  "/images/portfolio/kfc-csp/2.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-csp/3.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-csp/4.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-downtown-east/1.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/kfc-downtown-east/2.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/kfc-downtown-east/3.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-downtown-east/4.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-plq/1.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-plq/2.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-plq/3.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-plq/4.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-plq/5.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-plq/6.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/office-mbfc/1.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/office-mbfc/2.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/office-mbfc/3.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/office-mbfc/4.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/pizza-hut-tiong-bahru/1.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/pizza-hut-tiong-bahru/2.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/pizza-hut-tiong-bahru/3.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/pizza-hut-tiong-bahru/4.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/pizza-hut-tiong-bahru/5.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/pizza-hut-tiong-bahru/6.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/residential-bidadari/1.jpg": { w: 1600, h: 1236 },
  "/images/portfolio/residential-bidadari/2.jpg": { w: 1600, h: 932 },
  "/images/portfolio/residential-bidadari/3.jpg": { w: 1600, h: 1033 },
  "/images/portfolio/residential-bidadari/4.jpg": { w: 1198, h: 1600 },
  "/images/portfolio/residential-bidadari/5.jpg": { w: 1067, h: 1600 },
  "/images/portfolio/residential-bidadari/6.jpg": { w: 1177, h: 1600 },
  "/images/portfolio/residential-bidadari/7.jpg": { w: 831, h: 1600 },
  "/images/portfolio/residential-potong-pasir/1.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/residential-potong-pasir/2.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/residential-potong-pasir/3.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/residential-potong-pasir/4.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/residential-potong-pasir/5.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/residential-potong-pasir/6.jpg": { w: 1500, h: 2000 },
};

/** Landscape photos get a wide tile; portrait and square stay tall. */
export function isLandscape(src: string): boolean {
  const s = imageSizes[src];
  return s ? s.w / s.h > 1.15 : false;
}
