// AUTO-GENERATED by scripts/gen-image-sizes.py — do not edit by hand.
// Regenerate after adding, removing, or replacing portfolio photos:
//   python scripts/gen-image-sizes.py

export type ImageSize = { w: number; h: number };

export const imageSizes: Record<string, ImageSize> = {
  "/images/portfolio/kfc-amk/1.jpg": { w: 1600, h: 1200 },
  "/images/portfolio/kfc-amk/2.jpg": { w: 1600, h: 1200 },
  "/images/portfolio/kfc-compass-vale/1.jpg": { w: 658, h: 1600 },
  "/images/portfolio/kfc-csp/1.jpg": { w: 1125, h: 2000 },
  "/images/portfolio/kfc-csp/2.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-downtown-east/1.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/kfc-downtown-east/2.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/kfc-downtown-east/3.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-downtown-east/4.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-plq/1.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-plq/2.jpg": { w: 1080, h: 2000 },
  "/images/portfolio/kfc-plq/3.jpg": { w: 1200, h: 1560 },
  "/images/portfolio/kfc-plq/4.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/kfc-plq/5.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/office-mbfc/1.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/office-mbfc/2.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/office-mbfc/3.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/office-mbfc/4.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/office-toa-payoh/1.jpg": { w: 1536, h: 1680 },
  "/images/portfolio/office-toa-payoh/2.jpg": { w: 1536, h: 1638 },
  "/images/portfolio/pizza-hut-downtown-east/1.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/pizza-hut-downtown-east/2.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/pizza-hut-tiong-bahru/1.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/pizza-hut-tiong-bahru/2.jpg": { w: 1926, h: 1290 },
  "/images/portfolio/residential-bidadari/1.jpg": { w: 1600, h: 1236 },
  "/images/portfolio/residential-bidadari/2.jpg": { w: 1600, h: 932 },
  "/images/portfolio/residential-bidadari/3.jpg": { w: 1600, h: 1033 },
  "/images/portfolio/residential-bidadari/4.jpg": { w: 1198, h: 1600 },
  "/images/portfolio/residential-bidadari/5.jpg": { w: 1067, h: 1600 },
  "/images/portfolio/residential-bidadari/6.jpg": { w: 1177, h: 1600 },
  "/images/portfolio/residential-bidadari/7.jpg": { w: 831, h: 1600 },
  "/images/portfolio/residential-potong-pasir/1.jpg": { w: 1536, h: 1556 },
  "/images/portfolio/residential-potong-pasir/2.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/residential-potong-pasir/3.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/residential-potong-pasir/4.jpg": { w: 2000, h: 1500 },
  "/images/portfolio/residential-potong-pasir/5.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/residential-potong-pasir/6.jpg": { w: 1500, h: 2000 },
  "/images/portfolio/september-coffee/1.jpg": { w: 1179, h: 1494 },
  "/images/portfolio/september-coffee/2.jpg": { w: 2048, h: 1536 },
  "/images/portfolio/september-coffee/3.jpg": { w: 1536, h: 2048 },
  "/images/portfolio/september-coffee/4.jpg": { w: 1434, h: 1536 },
  "/images/portfolio/september-coffee/5.jpg": { w: 2048, h: 1536 },
  "/images/portfolio/september-coffee/6.jpg": { w: 1002, h: 1465 },
  "/images/portfolio/september-coffee/7.jpg": { w: 1069, h: 1600 },
  "/images/portfolio/september-coffee/8.jpg": { w: 1068, h: 1600 },
  "/images/portfolio/september-coffee/9.jpg": { w: 1066, h: 1600 },
  "/images/portfolio/september-coffee/10.jpg": { w: 1536, h: 2048 },
  "/images/portfolio/september-coffee/11.jpg": { w: 2048, h: 1536 },
};

/** Landscape photos get a wide tile; portrait and square stay tall. */
export function isLandscape(src: string): boolean {
  const s = imageSizes[src];
  return s ? s.w / s.h > 1.15 : false;
}
