"""Generate src/lib/data/image-sizes.ts from the portfolio images on disk.

The gallery needs each photo's orientation to decide whether it gets a wide
(2-column) or tall (1-column) tile. Rather than hand-maintaining dimensions in
projects.ts — which drifts every time photos are re-curated — this reads the
actual files and regenerates the map.

Run from the repo root:  python scripts/gen-image-sizes.py
"""

import os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.dirname(HERE)
SRC_DIR = os.path.join(WEB, "public", "images", "portfolio")
OUT = os.path.join(WEB, "src", "lib", "data", "image-sizes.ts")

rows = []
for slug in sorted(os.listdir(SRC_DIR)):
    d = os.path.join(SRC_DIR, slug)
    if not os.path.isdir(d):
        continue
    for f in sorted(os.listdir(d), key=lambda x: int(x.split(".")[0])):
        w, h = Image.open(os.path.join(d, f)).size
        rows.append((f"/images/portfolio/{slug}/{f}", w, h))

lines = [
    "// AUTO-GENERATED by scripts/gen-image-sizes.py — do not edit by hand.",
    "// Regenerate after adding, removing, or replacing portfolio photos:",
    "//   python scripts/gen-image-sizes.py",
    "",
    "export type ImageSize = { w: number; h: number };",
    "",
    "export const imageSizes: Record<string, ImageSize> = {",
]
for src, w, h in rows:
    lines.append(f'  "{src}": {{ w: {w}, h: {h} }},')
lines += [
    "};",
    "",
    "/** Landscape photos get a wide tile; portrait and square stay tall. */",
    "export function isLandscape(src: string): boolean {",
    "  const s = imageSizes[src];",
    "  return s ? s.w / s.h > 1.15 : false;",
    "}",
    "",
]

with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(lines))

land = sum(1 for _, w, h in rows if w / h > 1.15)
print(f"Wrote {OUT}")
print(f"  {len(rows)} images  |  {land} landscape  |  {len(rows) - land} portrait/square")
